query GetSellerList($search : String, $pagination : String) {
  getSellerList(search : $search, pagination: $pagination) @context(provider: "borntwo.helloworldtest"){
    count
    list {
      id
      SellerId
      Name
      Email
      Description
      ExchangeReturnPolicy
      DeliveryPolicy
      UseHybridPaymentOptions
      UserName
      Password
      SecutityPrivacyPolicy
      CNPJ
      CSCIdentification
      ArchiveId
      UrlLogo
      ProductCommissionPercentage
      FreightCommissionPercentage
      FulfillmentEndpoint
      CatalogSystemEndpoint
      IsActive
      Invited
      noOfInvites
      FulfillmentSellerId
      SellerType
      IsBetterScope
      creationDate
    }
  }
}
